baseURL = "https://personal-website-fda17.firebaseapp.com/"
languageCode = "en-us"
title = "Rich Tillis - SW Dev"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "" 

[params]
    # theme_color = "#006699"
    author = "Calin Tataru, Alexis Collado, and Rich TIllis"
    description = "Fullstack Software Engineer"
    profilePic = "/images/tillis_headshot.jpg"
    githubUsername = "#"
    accent = "#006699"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["java", "javascript"]

[params.hero]
    enable = true
    avatar = "tillis_headshot.jpg"
    subtitle = "I'm Rich, a software engineer."
    hero_right = ["Hello World.", "I'm a fullstack software developer.", "Always building. Always learning."]
    # resume = "ResumeCollado.pdf"  

[params.case_studies]
    enable = true
    title = "Recent Projects"
    subtitle = "Fun Stuff I've Been Building"   

[params.favicon]
    enable=true

[[menu.main]]
    url = "/" 
    name = "Home"
    weight = 1

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 2

#[[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rich@richtillis.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/richtillis/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/richtillis/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/richtillis/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/4577397/richtillis/"
    name = "stack-overflow"
    weight = 5
